version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-language-learning-dev
    command: fastapi dev main.py --host 0.0.0.0 --port 8002
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - ./app:/app
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - .git/
            - __pycache__/
            - .pytest_cache/
            - .mypy_cache/
            - .venv/
            - .idea/
            - .vscode/
            - node_modules/
        - action: rebuild
          path: ./requirements.txt
        - action: rebuild
          path: ./Dockerfile